# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FunctionalReactivePixels' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FunctionalReactivePixels

  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'libextobjc', '~> 0.4.1'
  pod '500px-iOS-api', '~> 1.0.5'
  pod 'SVProgressHUD', '~> 2.2.5'
end
